server:
  port: 8762
eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  application:
    name: Api GateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:*} # With '*' we allow all origins. We can restrict by indicating domains or ip + port, e.g. http://localhost:3000 (where our front is, or a Vercel domain)
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        - id: landing_formularios_registro_id
          uri: https://canelaaccounmanager.up.railway.app/form/send
          predicates:
          - Path=/form/send
        - id: landing_formularios_buyer_info
          uri: https://canelaaccounmanager.up.railway.app/payment/buyer
          predicates:
          - Path=/payment/buyer
        - id: landing_formularios_card_info
          uri: https://canelaaccounmanager.up.railway.app/payment/card
          predicates:
          - Path=/payment/card
        - id: canela_platform_get_planes
          uri: https://canelaplanbackend-production.up.railway.app/api/planes
          predicates:
          - Path=/api/planes
management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include:
          - '*'