spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: landing_formularios_registro_id
            uri: ${POST_ROUTE_URI:http://localhost:8082}
            predicates:
              - Path=/formularios/agregar/**
            filters:
              - PrefixPath=/accountManager
          - id: landing_formularios_id
            uri: ${GET_ROUTE_URI:http://localhost:8082}
            predicates:
              - Path=/formularios/**
            filters:
              - PrefixPath=/accountManager
          - id: landing_formularios_modificar_id
            uri: ${PUT_ROUTE_URI:http://localhost:8082}
            predicates:
              - Path=/formularios/id/modificar**
            filters:
              - PrefixPath=/accountManager