server:
  port: 8762

eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  application:
    name: Api GateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:*}
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        - id: canela_plan_backend
          uri: https://modulocuentasplan-qa.up.railway.app
          predicates:
            - Path=/plans/**
        - id: canela_auth
          uri: https://canelaauth-qa.up.railway.app/
          predicates:
            - Path=/api/talentsoft/auth/**
        - id: canela_roles
          uri: https://canelaauth-qa.up.railway.app/
          predicates:
            - Path=/api/talentsoft/roles/**
        - id: canela_account_manager_microservice
          uri: https://canelaaccountmanagermicroservice-qa.up.railway.app
          predicates:
            - Path=/accountmanager/**
        - id: landing_formularios_registro_id
          uri: https://canelamarketingmicroservice-qa.up.railway.app/possibleclient/send
          predicates:
            - Path=/possibleclient/send
        - id: canela_get_possible_clients
          uri: https://canelamarketingmicroservice-qa.up.railway.app/possibleclient/list
          predicates:
            - Path=/possibleclient/list
        - id: canela_get_existing_marketing_statuses
          uri: https://canelamarketingmicroservice-qa.up.railway.app/marketingstatus/list
          predicates:
            - Path=/marketingstatus/list
        - id: canela_save_possible_client_status_changes
          uri: https://canelamarketingmicroservice-qa.up.railway.app/possibleclient/saveAll
          predicates:
            - Path=/possibleclient/saveAll
        - id: canela_save_new_marketing_status
          uri: http://localhost:8084/marketingstatus/save
          predicates:
            - Path=/marketingstatus/save
        - id: canela_delete_marketing_status
          uri: https://canelamarketingmicroservice-qa.up.railway.app/marketingstatus/delete/**
          predicates:
            - Path=/marketingstatus/delete/**
        - id: landing_obtener_planes
          uri: https://canelaaccounmanagermicroservice-qa.up.railway.app/plan/list
          predicates:
            - Path=/plan/list
        - id: landing_create_user
          uri: http://localhost:8083/user/save
          predicates:
            - Path=/user/save
        - id: landing_create_company
          uri: https://canelaaccounmanagermicroservice-qa.up.railway.app/company/save
          predicates:
            - Path=/company/save
        - id: canela_platfotm_get_all_users_with_roles
          uri: https://canelausermanagementmicroservice-qa.up.railway.app/user/find_all_with_roles
          predicates:
            - Path=/user/find_all_with_roles
        - id: canela_platfotm_save_all_users_with_roles
          uri: https://canelausermanagementmicroservice-qa.up.railway.app/rol/update_all_users_roles
          predicates:
            - Path=/rol/update_all_users_roles
        - id: landing_formularios_buyer_info
          uri: https://canelaaccounmanagermicroservice-qa.up.railway.app/payment/buyer
          predicates:
            - Path=/payment/buyer
        - id: landing_formularios_card_info
          uri: https://canelaaccounmanagermicroservice-qa.up.railway.app/payment/card
          predicates:
            - Path=/payment/card
        - id: modulo_cuentas_facturation
          uri: https://modulocuentasfacturation-qa.up.railway.app
          predicates:
            - Path=/facturations/**
        - id: modulo_servicios
          uri: https://canelaaccounmanagermicroservice-qa.up.railway.app
          predicates:
            - Path=/services/**
        - id: canela_platfotm_get_all_companies
          uri: https://canelaaccounmanagermicroservice-qa.up.railway.app/company/list
          predicates:
            - Path=/company/list
        - id: canela_platform_account_manager_save_card
          uri: s://canelaaccounmanagermicroservice-qa.up.railway.app/card/save
          predicates:
            - Path=/card/save


management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include:
          - '*'
logging:
  level:
    root: INFO  # Cambia a DEBUG para una salida más detallada en el ambiente de desarrollo
    org.springframework.cloud.gateway: DEBUG  # Logging específico para Spring Cloud Gateway
    org.springframework.web: DEBUG  # Para ver detalles de las peticiones web y respuestas
    org.springframework.security: INFO  # Si utilizas Spring Security
