
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "*"
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
      routes:
        - id: landing_formularios_registro_id
          uri: https://canelaaccounmanager.up.railway.app/form/send
          predicates:
          - Path=/form/send
        - id: landing_formularios_buyer_info
          uri: https://canelaaccounmanager.up.railway.app/payment/buyer
          predicates:
          - Path=/payment/buyer
        - id: landing_formularios_card_info
          uri: https://canelaaccounmanager.up.railway.app/payment/card
          predicates:
          - Path=/payment/card
        - id: canela_platform_get_planes
          uri: https://canelaplanbackend-production.up.railway.app/api/planes
          predicates:
          - Path=/api/planes

